### (1) 신규 회원가입
# @name register
POST http://localhost:3001/api/register
Content-Type: application/json

{
  "email": "test-user@avocado.com",
  "pw": "safe_password123!",
  "name": "김아보",
  "age": 28,
  "gender": "female"
}

###

### (2) 로그인 및 토큰 발급
# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "test-user@avocado.com",
  "pw": "safe_password123!"
}

###

### (3) 사용자 정보 조회 (인증 테스트)
# 로그인해서 받은 토큰을 사용합니다.
GET http://localhost:3001/api/user/1
Authorization: Bearer {{login.response.body.token}}

###

### (4) 음성 변환(TTS) 최종 테스트
# 로그인해서 받은 토큰으로 인증하고, AI 서버에 음성 변환을 요청합니다.
POST http://localhost:3001/api/convert
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "text": "티티에스 변환 성공공",
  "modelId": "default_male.wav"
}

### (5) 커스텀 목소리 생성을 위한 파일 업로드
# @name uploadVoice
POST http://localhost:3001/api/models/custom
Authorization: Bearer {{login.response.body.token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="voiceSample"; filename="jjanggu.wav"
Content-Type: audio/wav

< F:/avocado/ai/voices/jjanggu.wav

------WebKitFormBoundary7MA4YWxkTrZu0gW--



### 내 모델 목록 조회
GET http://localhost:3001/api/models/my-models
Authorization: Bearer YOUR_TOKEN_HERE